name: CI
on:
  push:
    branches:
      - main
      - nightly
  pull_request:
    branches: 
      - "*"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update rustup
      run: rustup self update
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install 1.81 -c rust-docs
        rustup default 1.81
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL  https://github.com/rust-lang/mdBook/releases/download/v0.5.4/mdbook-v0.5.4-x86_64-unknown-linux-gnu.tar.gz| tar -xz --directory=bin
        echo "$(pwd)/bin" >> "${GITHUB_PATH}"
    - name: Report versions
      run: |
        rustup --version
        rustc -Vv
        mdbook --version
      # if build pass, test pass :-)
    - name: run test
      run: mdbook build

    # mdBook does not currently have particularly good support for “external”
    # crates. To make the test suite work correctly with `trpl`, we must first
    # build `trpl` itself (`mdbook` will not do it), and then explicitly pass
    # its `deps` path as a library search path for `mdbook test`. That will make
    # sure all the crates can be resolved when running the tests.

    # - name: Build `trpl` crate
    #   run: |
    #     cd packages/trpl
    #     cargo build
    # - name: Run tests
    #   run:
    #     mdbook test --library-path packages/trpl/target/debug/deps
